"""Branch master generator for the synthetic retail banking universe.

Defines the static branches across major metro and urban Indian locations.
"""

from datetime import date

import polars as pl

# List of pre-defined branches
BRANCH_DATA = [
    # Metro branches — Tier 1 cities, highest customer density
    {
        "branch_code": "B001",
        "branch_name": "Mumbai Fort",
        "city": "Mumbai",
        "state": "Maharashtra",
        "region": "West",
        "branch_type": "Metro",
        "open_date": date(2010, 1, 1),
        "closure_date": None,
        "customer_weight": 18,
    },
    {
        "branch_code": "B002",
        "branch_name": "Mumbai Bandra Kurla Complex",
        "city": "Mumbai",
        "state": "Maharashtra",
        "region": "West",
        "branch_type": "Metro",
        "open_date": date(2011, 4, 1),
        "closure_date": None,
        "customer_weight": 14,
    },
    {
        "branch_code": "B003",
        "branch_name": "Bengaluru MG Road",
        "city": "Bengaluru",
        "state": "Karnataka",
        "region": "South",
        "branch_type": "Metro",
        "open_date": date(2012, 6, 1),
        "closure_date": None,
        "customer_weight": 16,
    },
    {
        "branch_code": "B004",
        "branch_name": "Bengaluru Whitefield",
        "city": "Bengaluru",
        "state": "Karnataka",
        "region": "South",
        "branch_type": "Metro",
        "open_date": date(2015, 3, 1),
        "closure_date": None,
        "customer_weight": 12,
    },
    {
        "branch_code": "B005",
        "branch_name": "Delhi Connaught Place",
        "city": "Delhi",
        "state": "Delhi",
        "region": "North",
        "branch_type": "Metro",
        "open_date": date(2011, 3, 1),
        "closure_date": None,
        "customer_weight": 15,
    },
    {
        "branch_code": "B006",
        "branch_name": "Delhi Dwarka",
        "city": "Delhi",
        "state": "Delhi",
        "region": "North",
        "branch_type": "Metro",
        "open_date": date(2014, 7, 1),
        "closure_date": None,
        "customer_weight": 10,
    },
    {
        "branch_code": "B007",
        "branch_name": "Kolkata Salt Lake",
        "city": "Kolkata",
        "state": "West Bengal",
        "region": "East",
        "branch_type": "Metro",
        "open_date": date(2013, 9, 1),
        "closure_date": None,
        "customer_weight": 11,
    },
    {
        "branch_code": "B008",
        "branch_name": "Chennai T-Nagar",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "region": "South",
        "branch_type": "Metro",
        "open_date": date(2014, 7, 1),
        "closure_date": None,
        "customer_weight": 12,
    },
    {
        "branch_code": "B009",
        "branch_name": "Hyderabad Gachibowli",
        "city": "Hyderabad",
        "state": "Telangana",
        "region": "South",
        "branch_type": "Metro",
        "open_date": date(2016, 11, 1),
        "closure_date": None,
        "customer_weight": 11,
    },
    # Urban branches — Tier 2 cities, moderate customer density
    {
        "branch_code": "B010",
        "branch_name": "Pune Shivaji Nagar",
        "city": "Pune",
        "state": "Maharashtra",
        "region": "West",
        "branch_type": "Urban",
        "open_date": date(2015, 2, 1),
        "closure_date": None,
        "customer_weight": 8,
    },
    {
        "branch_code": "B011",
        "branch_name": "Pune Hinjewadi",
        "city": "Pune",
        "state": "Maharashtra",
        "region": "West",
        "branch_type": "Urban",
        "open_date": date(2017, 9, 1),
        "closure_date": None,
        "customer_weight": 6,
    },
    {
        "branch_code": "B012",
        "branch_name": "Ahmedabad Satellite",
        "city": "Ahmedabad",
        "state": "Gujarat",
        "region": "West",
        "branch_type": "Urban",
        "open_date": date(2017, 5, 1),
        "closure_date": None,
        "customer_weight": 7,
    },
    {
        "branch_code": "B013",
        "branch_name": "Lucknow Hazratganj",
        "city": "Lucknow",
        "state": "Uttar Pradesh",
        "region": "North",
        "branch_type": "Urban",
        "open_date": date(2018, 8, 1),
        "closure_date": None,
        "customer_weight": 6,
    },
    {
        "branch_code": "B014",
        "branch_name": "Jaipur C-Scheme",
        "city": "Jaipur",
        "state": "Rajasthan",
        "region": "North",
        "branch_type": "Urban",
        "open_date": date(2019, 10, 1),
        "closure_date": None,
        "customer_weight": 6,
    },
    {
        "branch_code": "B015",
        "branch_name": "Kochi Marine Drive",
        "city": "Kochi",
        "state": "Kerala",
        "region": "South",
        "branch_type": "Urban",
        "open_date": date(2018, 3, 1),
        "closure_date": None,
        "customer_weight": 5,
    },
    {
        "branch_code": "B016",
        "branch_name": "Trivandrum MG Road",
        "city": "Trivandrum",
        "state": "Kerala",
        "region": "South",
        "branch_type": "Urban",
        "open_date": date(2018, 7, 1),
        "closure_date": None,
        "customer_weight": 5,
    },
    {
        "branch_code": "B017",
        "branch_name": "Chandigarh Sector 17",
        "city": "Chandigarh",
        "state": "Punjab",
        "region": "North",
        "branch_type": "Urban",
        "open_date": date(2019, 6, 1),
        "closure_date": None,
        "customer_weight": 5,
    },
    {
        "branch_code": "B018",
        "branch_name": "Bhopal MP Nagar",
        "city": "Bhopal",
        "state": "Madhya Pradesh",
        "region": "Central",
        "branch_type": "Urban",
        "open_date": date(2020, 1, 1),
        "closure_date": None,
        "customer_weight": 4,
    },
    {
        "branch_code": "B019",
        "branch_name": "Nagpur Dharampeth",
        "city": "Nagpur",
        "state": "Maharashtra",
        "region": "West",
        "branch_type": "Urban",
        "open_date": date(2020, 6, 1),
        "closure_date": None,
        "customer_weight": 4,
    },
    {
        "branch_code": "B020",
        "branch_name": "Visakhapatnam MVP Colony",
        "city": "Visakhapatnam",
        "state": "Andhra Pradesh",
        "region": "South",
        "branch_type": "Urban",
        "open_date": date(2021, 2, 1),
        "closure_date": None,
        "customer_weight": 4,
    },
    {
        "branch_code": "B021",
        "branch_name": "Surat Ring Road",
        "city": "Surat",
        "state": "Gujarat",
        "region": "West",
        "branch_type": "Urban",
        "open_date": date(2021, 8, 1),
        "closure_date": None,
        "customer_weight": 4,
    },
]


def generate_branches() -> pl.DataFrame:
    """Generates the static branch master DataFrame.

    Returns:
        pl.DataFrame: The branch master table.
    """
    return pl.DataFrame(
        BRANCH_DATA,
        schema={
            "branch_code": pl.String,
            "branch_name": pl.String,
            "city": pl.String,
            "state": pl.String,
            "region": pl.String,
            "branch_type": pl.String,
            "open_date": pl.Date,
            "closure_date": pl.Date,
            "customer_weight": pl.Int64,
        },
    )
